// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_ExampleGalleryDesktop_Direct3DInterop_1_H
#define WINRT_ExampleGalleryDesktop_Direct3DInterop_1_H
#include "winrt/impl/ExampleGalleryDesktop_Direct3DInterop.0.h"
WINRT_EXPORT namespace winrt::ExampleGalleryDesktop_Direct3DInterop
{
    struct __declspec(empty_bases) IClass :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClass>
    {
        IClass(std::nullptr_t = nullptr) noexcept {}
        IClass(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
