// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_ExampleGalleryDesktop_Direct3DInterop_2_H
#define WINRT_ExampleGalleryDesktop_Direct3DInterop_2_H
#include "winrt/impl/ExampleGalleryDesktop_Direct3DInterop.1.h"
WINRT_EXPORT namespace winrt::ExampleGalleryDesktop_Direct3DInterop
{
    struct __declspec(empty_bases) Class : winrt::ExampleGalleryDesktop_Direct3DInterop::IClass
    {
        Class(std::nullptr_t) noexcept {}
        Class(void* ptr, take_ownership_from_abi_t) noexcept : winrt::ExampleGalleryDesktop_Direct3DInterop::IClass(ptr, take_ownership_from_abi) {}
        Class();
    };
}
#endif
