// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_Printing_2_H
#define WINRT_Microsoft_Graphics_Canvas_Printing_2_H
#include "winrt/impl/Microsoft.Graphics.Canvas.1.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.Graphics.Printing.1.h"
#include "winrt/impl/Microsoft.Graphics.Canvas.Printing.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::Printing
{
    struct __declspec(empty_bases) CanvasPreviewEventArgs : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPreviewEventArgs
    {
        CanvasPreviewEventArgs(std::nullptr_t) noexcept {}
        CanvasPreviewEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPreviewEventArgs(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CanvasPrintDeferral : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintDeferral
    {
        CanvasPrintDeferral(std::nullptr_t) noexcept {}
        CanvasPrintDeferral(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintDeferral(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CanvasPrintDocument : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintDocument
    {
        CanvasPrintDocument(std::nullptr_t) noexcept {}
        CanvasPrintDocument(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintDocument(ptr, take_ownership_from_abi) {}
        CanvasPrintDocument();
        explicit CanvasPrintDocument(winrt::Microsoft::Graphics::Canvas::CanvasDevice const& device);
    };
    struct __declspec(empty_bases) CanvasPrintEventArgs : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintEventArgs
    {
        CanvasPrintEventArgs(std::nullptr_t) noexcept {}
        CanvasPrintEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintEventArgs(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CanvasPrintTaskOptionsChangedEventArgs : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintTaskOptionsChangedEventArgs
    {
        CanvasPrintTaskOptionsChangedEventArgs(std::nullptr_t) noexcept {}
        CanvasPrintTaskOptionsChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintTaskOptionsChangedEventArgs(ptr, take_ownership_from_abi) {}
    };
}
#endif
