// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_UI_Input_1_H
#define WINRT_Microsoft_UI_Input_1_H
#include "winrt/impl/Microsoft.UI.Input.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Input
{
    struct __declspec(empty_bases) IKeyboardInputStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IKeyboardInputStatics>
    {
        IKeyboardInputStatics(std::nullptr_t = nullptr) noexcept {}
        IKeyboardInputStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
