// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_Geometry_1_H
#define WINRT_Microsoft_Graphics_Canvas_Geometry_1_H
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Microsoft.Graphics.Canvas.Geometry.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::Geometry
{
    struct __declspec(empty_bases) ICanvasCachedGeometry :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasCachedGeometry>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Geometry::ICanvasCachedGeometry, winrt::Windows::Foundation::IClosable>
    {
        ICanvasCachedGeometry(std::nullptr_t = nullptr) noexcept {}
        ICanvasCachedGeometry(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasCachedGeometryStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasCachedGeometryStatics>
    {
        ICanvasCachedGeometryStatics(std::nullptr_t = nullptr) noexcept {}
        ICanvasCachedGeometryStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasGeometry :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasGeometry>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Geometry::ICanvasGeometry, winrt::Windows::Foundation::IClosable>
    {
        ICanvasGeometry(std::nullptr_t = nullptr) noexcept {}
        ICanvasGeometry(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasGeometryStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasGeometryStatics>
    {
        ICanvasGeometryStatics(std::nullptr_t = nullptr) noexcept {}
        ICanvasGeometryStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasGradientMesh :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasGradientMesh>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Geometry::ICanvasGradientMesh, winrt::Windows::Foundation::IClosable>
    {
        ICanvasGradientMesh(std::nullptr_t = nullptr) noexcept {}
        ICanvasGradientMesh(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasGradientMeshFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasGradientMeshFactory>
    {
        ICanvasGradientMeshFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasGradientMeshFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasGradientMeshStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasGradientMeshStatics>
    {
        ICanvasGradientMeshStatics(std::nullptr_t = nullptr) noexcept {}
        ICanvasGradientMeshStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasPathBuilder :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPathBuilder>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Geometry::ICanvasPathBuilder, winrt::Windows::Foundation::IClosable>
    {
        ICanvasPathBuilder(std::nullptr_t = nullptr) noexcept {}
        ICanvasPathBuilder(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasPathBuilderFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPathBuilderFactory>
    {
        ICanvasPathBuilderFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasPathBuilderFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasPathReceiver :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPathReceiver>
    {
        ICanvasPathReceiver(std::nullptr_t = nullptr) noexcept {}
        ICanvasPathReceiver(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasStrokeStyle :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasStrokeStyle>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Geometry::ICanvasStrokeStyle, winrt::Windows::Foundation::IClosable>
    {
        ICanvasStrokeStyle(std::nullptr_t = nullptr) noexcept {}
        ICanvasStrokeStyle(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
