// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_UI_2_H
#define WINRT_Microsoft_Graphics_Canvas_UI_2_H
#include "winrt/impl/Microsoft.Graphics.Canvas.UI.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::UI
{
    struct __declspec(empty_bases) CanvasCreateResourcesEventArgs : winrt::Microsoft::Graphics::Canvas::UI::ICanvasCreateResourcesEventArgs
    {
        CanvasCreateResourcesEventArgs(std::nullptr_t) noexcept {}
        CanvasCreateResourcesEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::ICanvasCreateResourcesEventArgs(ptr, take_ownership_from_abi) {}
        explicit CanvasCreateResourcesEventArgs(winrt::Microsoft::Graphics::Canvas::UI::CanvasCreateResourcesReason const& createResourcesReason);
    };
}
#endif
