// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_UI_Composition_2_H
#define WINRT_Microsoft_Graphics_Canvas_UI_Composition_2_H
#include "winrt/impl/Microsoft.Graphics.Canvas.1.h"
#include "winrt/impl/Microsoft.UI.Composition.1.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Microsoft.Graphics.Canvas.UI.Composition.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::UI::Composition
{
    struct CanvasComposition
    {
        CanvasComposition() = delete;
        static auto CreateCompositionGraphicsDevice(winrt::Microsoft::UI::Composition::Compositor const& compositor, winrt::Microsoft::Graphics::Canvas::CanvasDevice const& canvasDevice);
        static auto CreateCompositionSurfaceForSwapChain(winrt::Microsoft::UI::Composition::Compositor const& compositor, winrt::Microsoft::Graphics::Canvas::CanvasSwapChain const& swapChain);
        static auto GetCanvasDevice(winrt::Microsoft::UI::Composition::CompositionGraphicsDevice const& graphicsDevice);
        static auto SetCanvasDevice(winrt::Microsoft::UI::Composition::CompositionGraphicsDevice const& graphicsDevice, winrt::Microsoft::Graphics::Canvas::CanvasDevice const& canvasDevice);
        static auto CreateDrawingSession(winrt::Microsoft::UI::Composition::CompositionDrawingSurface const& drawingSurface);
        static auto CreateDrawingSession(winrt::Microsoft::UI::Composition::CompositionDrawingSurface const& drawingSurface, winrt::Windows::Foundation::Rect const& updateRect);
        static auto CreateDrawingSession(winrt::Microsoft::UI::Composition::CompositionDrawingSurface const& drawingSurface, winrt::Windows::Foundation::Rect const& updateRectInPixels, float dpi);
        static auto Resize(winrt::Microsoft::UI::Composition::CompositionDrawingSurface const& drawingSurface, winrt::Windows::Foundation::Size const& sizeInPixels);
    };
}
#endif
