// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

void* winrt_make_ExampleGalleryDesktop_Direct3DInterop_Class()
{
    return winrt::detach_abi(winrt::make<winrt::ExampleGalleryDesktop_Direct3DInterop::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::ExampleGalleryDesktop_Direct3DInterop
{
    Class::Class() :
        Class(make<ExampleGalleryDesktop_Direct3DInterop::implementation::Class>())
    {
    }
}
