// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_Svg_1_H
#define WINRT_Microsoft_Graphics_Canvas_Svg_1_H
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Microsoft.Graphics.Canvas.Svg.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::Svg
{
    struct __declspec(empty_bases) ICanvasSvgAttribute :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgAttribute>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgAttribute, winrt::Windows::Foundation::IClosable>
    {
        ICanvasSvgAttribute(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgAttribute(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgDocument :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgDocument>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgDocument, winrt::Windows::Foundation::IClosable>
    {
        ICanvasSvgDocument(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgDocument(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgDocumentFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgDocumentFactory>
    {
        ICanvasSvgDocumentFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgDocumentFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgDocumentStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgDocumentStatics>
    {
        ICanvasSvgDocumentStatics(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgDocumentStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgElement :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgElement>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgElement, winrt::Windows::Foundation::IClosable>
    {
        ICanvasSvgElement(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgElement(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgNamedElement :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgNamedElement>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgNamedElement, winrt::Windows::Foundation::IClosable, winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgElement>
    {
        ICanvasSvgNamedElement(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgNamedElement(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgPaintAttribute :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgPaintAttribute>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgPaintAttribute, winrt::Windows::Foundation::IClosable, winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgAttribute>
    {
        ICanvasSvgPaintAttribute(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgPaintAttribute(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgPathAttribute :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgPathAttribute>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgPathAttribute, winrt::Windows::Foundation::IClosable, winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgAttribute>
    {
        ICanvasSvgPathAttribute(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgPathAttribute(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgPointsAttribute :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgPointsAttribute>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgPointsAttribute, winrt::Windows::Foundation::IClosable, winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgAttribute>
    {
        ICanvasSvgPointsAttribute(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgPointsAttribute(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgStrokeDashArrayAttribute :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgStrokeDashArrayAttribute>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgStrokeDashArrayAttribute, winrt::Windows::Foundation::IClosable, winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgAttribute>
    {
        ICanvasSvgStrokeDashArrayAttribute(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgStrokeDashArrayAttribute(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICanvasSvgTextElement :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSvgTextElement>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Svg::ICanvasSvgTextElement, winrt::Windows::Foundation::IClosable>
    {
        ICanvasSvgTextElement(std::nullptr_t = nullptr) noexcept {}
        ICanvasSvgTextElement(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
