// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_UI_Composition_1_H
#define WINRT_Microsoft_Graphics_Canvas_UI_Composition_1_H
#include "winrt/impl/Microsoft.Graphics.Canvas.UI.Composition.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::UI::Composition
{
    struct __declspec(empty_bases) ICanvasCompositionStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasCompositionStatics>
    {
        ICanvasCompositionStatics(std::nullptr_t = nullptr) noexcept {}
        ICanvasCompositionStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
