// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_UI_Xaml_0_H
#define WINRT_Microsoft_Graphics_Canvas_UI_Xaml_0_H
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas
{
    enum class CanvasAlphaMode : int32_t;
    struct CanvasDevice;
    struct CanvasDrawingSession;
    struct CanvasSwapChain;
    struct ICanvasResourceCreator;
    struct ICanvasResourceCreatorWithDpi;
}
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::UI
{
    struct CanvasCreateResourcesEventArgs;
}
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Media::Imaging
{
    struct VirtualSurfaceImageSource;
}
WINRT_EXPORT namespace winrt::Windows::Foundation
{
    struct EventRegistrationToken;
    struct Rect;
    struct Size;
    template <typename TSender, typename TResult> struct __declspec(empty_bases) TypedEventHandler;
}
WINRT_EXPORT namespace winrt::Windows::Graphics::Imaging
{
    struct BitmapSize;
}
WINRT_EXPORT namespace winrt::Windows::UI
{
    struct Color;
}
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::UI::Xaml
{
    struct ICanvasControl;
    struct ICanvasDrawEventArgs;
    struct ICanvasDrawEventArgsFactory;
    struct ICanvasImageSource;
    struct ICanvasImageSourceFactory;
    struct ICanvasRegionsInvalidatedEventArgs;
    struct ICanvasSwapChainPanel;
    struct ICanvasVirtualControl;
    struct ICanvasVirtualImageSource;
    struct ICanvasVirtualImageSourceFactory;
    struct CanvasControl;
    struct CanvasDrawEventArgs;
    struct CanvasImageSource;
    struct CanvasRegionsInvalidatedEventArgs;
    struct CanvasSwapChainPanel;
    struct CanvasVirtualControl;
    struct CanvasVirtualImageSource;
}
namespace winrt::impl
{
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgs>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgsFactory>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSourceFactory>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasRegionsInvalidatedEventArgs>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasSwapChainPanel>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSourceFactory>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasImageSource>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasRegionsInvalidatedEventArgs>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasSwapChainPanel>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualControl>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl> = L"Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs> = L"Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasImageSource> = L"Microsoft.Graphics.Canvas.UI.Xaml.CanvasImageSource";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasRegionsInvalidatedEventArgs> = L"Microsoft.Graphics.Canvas.UI.Xaml.CanvasRegionsInvalidatedEventArgs";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasSwapChainPanel> = L"Microsoft.Graphics.Canvas.UI.Xaml.CanvasSwapChainPanel";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualControl> = L"Microsoft.Graphics.Canvas.UI.Xaml.CanvasVirtualControl";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource> = L"Microsoft.Graphics.Canvas.UI.Xaml.CanvasVirtualImageSource";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasControl";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgs> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasDrawEventArgs";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgsFactory> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasDrawEventArgsFactory";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasImageSource";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSourceFactory> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasImageSourceFactory";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasRegionsInvalidatedEventArgs> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasRegionsInvalidatedEventArgs";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasSwapChainPanel> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasSwapChainPanel";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasVirtualControl";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasVirtualImageSource";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSourceFactory> = L"Microsoft.Graphics.Canvas.UI.Xaml.ICanvasVirtualImageSourceFactory";
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl>{ 0xF006E06D,0x79DB,0x484F,{ 0xB8,0x98,0x47,0x9C,0xF0,0x69,0xC0,0xF5 } }; // F006E06D-79DB-484F-B898-479CF069C0F5
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgs>{ 0xFB86169F,0x25D4,0x4551,{ 0xBD,0x8F,0x21,0x4B,0xEA,0xF0,0xAC,0x24 } }; // FB86169F-25D4-4551-BD8F-214BEAF0AC24
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgsFactory>{ 0x7299D72C,0xF8E4,0x4A2F,{ 0x9E,0x30,0x7C,0xDF,0xCC,0xF3,0x1C,0x44 } }; // 7299D72C-F8E4-4A2F-9E30-7CDFCCF31C44
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource>{ 0x3C35E87A,0xE881,0x4F44,{ 0xB0,0xD1,0x55,0x14,0x13,0xAE,0xC6,0x6D } }; // 3C35E87A-E881-4F44-B0D1-551413AEC66D
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSourceFactory>{ 0x8596BEDD,0xD7F7,0x4C6B,{ 0xB1,0xAD,0x41,0x94,0x90,0x35,0xE0,0x84 } }; // 8596BEDD-D7F7-4C6B-B1AD-41949035E084
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasRegionsInvalidatedEventArgs>{ 0x3A21A204,0xF52F,0x4E7A,{ 0x9B,0x3F,0x94,0x66,0x98,0x19,0xD9,0x81 } }; // 3A21A204-F52F-4E7A-9B3F-94669819D981
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasSwapChainPanel>{ 0xDBDCCB96,0x147E,0x4A82,{ 0xAF,0x3A,0xC9,0x1C,0x78,0x00,0xDA,0xA7 } }; // DBDCCB96-147E-4A82-AF3A-C91C7800DAA7
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl>{ 0x3C2B5177,0x7C61,0x41D2,{ 0x95,0xAE,0xFC,0xFC,0x92,0xFD,0x61,0x7A } }; // 3C2B5177-7C61-41D2-95AE-FCFC92FD617A
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource>{ 0xDF342987,0x4FE6,0x4BCD,{ 0xB8,0x85,0x2A,0xD3,0xE6,0xEF,0x9F,0xCE } }; // DF342987-4FE6-4BCD-B885-2AD3E6EF9FCE
    template <> inline constexpr guid guid_v<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSourceFactory>{ 0x2FE755A1,0x307A,0x4623,{ 0x92,0x50,0x29,0x59,0x04,0x85,0xBD,0xB6 } }; // 2FE755A1-307A-4623-9250-29590485BDB6
    template <> struct default_interface<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl>{ using type = winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl; };
    template <> struct default_interface<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs>{ using type = winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgs; };
    template <> struct default_interface<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasImageSource>{ using type = winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource; };
    template <> struct default_interface<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasRegionsInvalidatedEventArgs>{ using type = winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasRegionsInvalidatedEventArgs; };
    template <> struct default_interface<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasSwapChainPanel>{ using type = winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasSwapChainPanel; };
    template <> struct default_interface<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualControl>{ using type = winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl; };
    template <> struct default_interface<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource>{ using type = winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource; };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall add_CreateResources(void*, winrt::event_token*) noexcept = 0;
            virtual int32_t __stdcall remove_CreateResources(winrt::event_token) noexcept = 0;
            virtual int32_t __stdcall get_ReadyToDraw(bool*) noexcept = 0;
            virtual int32_t __stdcall add_Draw(void*, winrt::event_token*) noexcept = 0;
            virtual int32_t __stdcall remove_Draw(winrt::event_token) noexcept = 0;
            virtual int32_t __stdcall put_ClearColor(struct struct_Windows_UI_Color) noexcept = 0;
            virtual int32_t __stdcall get_ClearColor(struct struct_Windows_UI_Color*) noexcept = 0;
            virtual int32_t __stdcall Invalidate() noexcept = 0;
            virtual int32_t __stdcall get_Size(winrt::Windows::Foundation::Size*) noexcept = 0;
            virtual int32_t __stdcall RemoveFromVisualTree() noexcept = 0;
            virtual int32_t __stdcall get_UseSharedDevice(bool*) noexcept = 0;
            virtual int32_t __stdcall put_UseSharedDevice(bool) noexcept = 0;
            virtual int32_t __stdcall get_ForceSoftwareRenderer(bool*) noexcept = 0;
            virtual int32_t __stdcall put_ForceSoftwareRenderer(bool) noexcept = 0;
            virtual int32_t __stdcall get_CustomDevice(void**) noexcept = 0;
            virtual int32_t __stdcall put_CustomDevice(void*) noexcept = 0;
            virtual int32_t __stdcall get_DpiScale(float*) noexcept = 0;
            virtual int32_t __stdcall put_DpiScale(float) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgs>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_DrawingSession(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgsFactory>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall Create(void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall CreateDrawingSession(struct struct_Windows_UI_Color, void**) noexcept = 0;
            virtual int32_t __stdcall CreateDrawingSessionWithUpdateRectangle(struct struct_Windows_UI_Color, winrt::Windows::Foundation::Rect, void**) noexcept = 0;
            virtual int32_t __stdcall Recreate(void*) noexcept = 0;
            virtual int32_t __stdcall get_Size(winrt::Windows::Foundation::Size*) noexcept = 0;
            virtual int32_t __stdcall get_SizeInPixels(struct struct_Windows_Graphics_Imaging_BitmapSize*) noexcept = 0;
            virtual int32_t __stdcall get_AlphaMode(int32_t*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSourceFactory>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall CreateWithSize(void*, winrt::Windows::Foundation::Size, void**) noexcept = 0;
            virtual int32_t __stdcall CreateWithWidthAndHeight(void*, float, float, void**) noexcept = 0;
            virtual int32_t __stdcall CreateWithWidthAndHeightAndDpi(void*, float, float, float, void**) noexcept = 0;
            virtual int32_t __stdcall CreateWithWidthAndHeightAndDpiAndAlphaMode(void*, float, float, float, int32_t, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasRegionsInvalidatedEventArgs>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_InvalidatedRegions(uint32_t* __valueSize, winrt::Windows::Foundation::Rect**) noexcept = 0;
            virtual int32_t __stdcall get_VisibleRegion(winrt::Windows::Foundation::Rect*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasSwapChainPanel>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall put_SwapChain(void*) noexcept = 0;
            virtual int32_t __stdcall get_SwapChain(void**) noexcept = 0;
            virtual int32_t __stdcall RemoveFromVisualTree() noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall add_CreateResources(void*, winrt::event_token*) noexcept = 0;
            virtual int32_t __stdcall remove_CreateResources(winrt::event_token) noexcept = 0;
            virtual int32_t __stdcall get_ReadyToDraw(bool*) noexcept = 0;
            virtual int32_t __stdcall add_RegionsInvalidated(void*, winrt::event_token*) noexcept = 0;
            virtual int32_t __stdcall remove_RegionsInvalidated(winrt::event_token) noexcept = 0;
            virtual int32_t __stdcall put_ClearColor(struct struct_Windows_UI_Color) noexcept = 0;
            virtual int32_t __stdcall get_ClearColor(struct struct_Windows_UI_Color*) noexcept = 0;
            virtual int32_t __stdcall CreateDrawingSession(winrt::Windows::Foundation::Rect, void**) noexcept = 0;
            virtual int32_t __stdcall SuspendDrawingSession(void*) noexcept = 0;
            virtual int32_t __stdcall ResumeDrawingSession(void*) noexcept = 0;
            virtual int32_t __stdcall Invalidate() noexcept = 0;
            virtual int32_t __stdcall InvalidateRegion(winrt::Windows::Foundation::Rect) noexcept = 0;
            virtual int32_t __stdcall get_Size(winrt::Windows::Foundation::Size*) noexcept = 0;
            virtual int32_t __stdcall RemoveFromVisualTree() noexcept = 0;
            virtual int32_t __stdcall get_UseSharedDevice(bool*) noexcept = 0;
            virtual int32_t __stdcall put_UseSharedDevice(bool) noexcept = 0;
            virtual int32_t __stdcall get_ForceSoftwareRenderer(bool*) noexcept = 0;
            virtual int32_t __stdcall put_ForceSoftwareRenderer(bool) noexcept = 0;
            virtual int32_t __stdcall get_CustomDevice(void**) noexcept = 0;
            virtual int32_t __stdcall put_CustomDevice(void*) noexcept = 0;
            virtual int32_t __stdcall get_DpiScale(float*) noexcept = 0;
            virtual int32_t __stdcall put_DpiScale(float) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_Source(void**) noexcept = 0;
            virtual int32_t __stdcall CreateDrawingSession(struct struct_Windows_UI_Color, winrt::Windows::Foundation::Rect, void**) noexcept = 0;
            virtual int32_t __stdcall SuspendDrawingSession(void*) noexcept = 0;
            virtual int32_t __stdcall ResumeDrawingSession(void*) noexcept = 0;
            virtual int32_t __stdcall Invalidate() noexcept = 0;
            virtual int32_t __stdcall InvalidateRegion(winrt::Windows::Foundation::Rect) noexcept = 0;
            virtual int32_t __stdcall RaiseRegionsInvalidatedIfAny() noexcept = 0;
            virtual int32_t __stdcall add_RegionsInvalidated(void*, winrt::event_token*) noexcept = 0;
            virtual int32_t __stdcall remove_RegionsInvalidated(winrt::event_token) noexcept = 0;
            virtual int32_t __stdcall ResizeWithSize(winrt::Windows::Foundation::Size) noexcept = 0;
            virtual int32_t __stdcall ResizeWithWidthAndHeight(float, float) noexcept = 0;
            virtual int32_t __stdcall ResizeWithWidthAndHeightAndDpi(float, float, float) noexcept = 0;
            virtual int32_t __stdcall Recreate(void*) noexcept = 0;
            virtual int32_t __stdcall get_Size(winrt::Windows::Foundation::Size*) noexcept = 0;
            virtual int32_t __stdcall get_SizeInPixels(struct struct_Windows_Graphics_Imaging_BitmapSize*) noexcept = 0;
            virtual int32_t __stdcall get_AlphaMode(int32_t*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSourceFactory>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall CreateWithSize(void*, winrt::Windows::Foundation::Size, void**) noexcept = 0;
            virtual int32_t __stdcall CreateWithWidthAndHeight(void*, float, float, void**) noexcept = 0;
            virtual int32_t __stdcall CreateWithWidthAndHeightAndDpi(void*, float, float, float, void**) noexcept = 0;
            virtual int32_t __stdcall CreateWithWidthAndHeightAndDpiAndAlphaMode(void*, float, float, float, int32_t, void**) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasControl
    {
        WINRT_IMPL_AUTO(winrt::event_token) CreateResources(winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, winrt::Microsoft::Graphics::Canvas::UI::CanvasCreateResourcesEventArgs> const& value) const;
        using CreateResources_revoker = impl::event_revoker<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl, &impl::abi_t<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl>::remove_CreateResources>;
        [[nodiscard]] CreateResources_revoker CreateResources(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, winrt::Microsoft::Graphics::Canvas::UI::CanvasCreateResourcesEventArgs> const& value) const;
        WINRT_IMPL_AUTO(void) CreateResources(winrt::event_token const& token) const noexcept;
        [[nodiscard]] WINRT_IMPL_AUTO(bool) ReadyToDraw() const;
        WINRT_IMPL_AUTO(winrt::event_token) Draw(winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs> const& value) const;
        using Draw_revoker = impl::event_revoker<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl, &impl::abi_t<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl>::remove_Draw>;
        [[nodiscard]] Draw_revoker Draw(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl, winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs> const& value) const;
        WINRT_IMPL_AUTO(void) Draw(winrt::event_token const& token) const noexcept;
        WINRT_IMPL_AUTO(void) ClearColor(winrt::Windows::UI::Color const& value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::UI::Color) ClearColor() const;
        WINRT_IMPL_AUTO(void) Invalidate() const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::Foundation::Size) Size() const;
        WINRT_IMPL_AUTO(void) RemoveFromVisualTree() const;
        [[nodiscard]] WINRT_IMPL_AUTO(bool) UseSharedDevice() const;
        WINRT_IMPL_AUTO(void) UseSharedDevice(bool value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(bool) ForceSoftwareRenderer() const;
        WINRT_IMPL_AUTO(void) ForceSoftwareRenderer(bool value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasDevice) CustomDevice() const;
        WINRT_IMPL_AUTO(void) CustomDevice(winrt::Microsoft::Graphics::Canvas::CanvasDevice const& value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(float) DpiScale() const;
        WINRT_IMPL_AUTO(void) DpiScale(float ratio) const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasControl<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasDrawEventArgs
    {
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession) DrawingSession() const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgs>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasDrawEventArgs<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasDrawEventArgsFactory
    {
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs) Create(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession const& canvasDrawingSession) const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgsFactory>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasDrawEventArgsFactory<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasImageSource
    {
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession) CreateDrawingSession(winrt::Windows::UI::Color const& clearColor) const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession) CreateDrawingSession(winrt::Windows::UI::Color const& clearColor, winrt::Windows::Foundation::Rect const& updateRectangle) const;
        WINRT_IMPL_AUTO(void) Recreate(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::Foundation::Size) Size() const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::Graphics::Imaging::BitmapSize) SizeInPixels() const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasAlphaMode) AlphaMode() const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasImageSource<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasImageSourceFactory
    {
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasImageSource) CreateWithSize(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi const& resourceCreator, winrt::Windows::Foundation::Size const& size) const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasImageSource) CreateWithWidthAndHeight(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi const& resourceCreator, float width, float height) const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasImageSource) CreateWithWidthAndHeightAndDpi(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator, float width, float height, float dpi) const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasImageSource) CreateWithWidthAndHeightAndDpiAndAlphaMode(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator, float width, float height, float dpi, winrt::Microsoft::Graphics::Canvas::CanvasAlphaMode const& alphaMode) const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSourceFactory>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasImageSourceFactory<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasRegionsInvalidatedEventArgs
    {
        [[nodiscard]] WINRT_IMPL_AUTO(com_array<winrt::Windows::Foundation::Rect>) InvalidatedRegions() const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::Foundation::Rect) VisibleRegion() const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasRegionsInvalidatedEventArgs>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasRegionsInvalidatedEventArgs<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasSwapChainPanel
    {
        WINRT_IMPL_AUTO(void) SwapChain(winrt::Microsoft::Graphics::Canvas::CanvasSwapChain const& value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasSwapChain) SwapChain() const;
        WINRT_IMPL_AUTO(void) RemoveFromVisualTree() const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasSwapChainPanel>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasSwapChainPanel<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasVirtualControl
    {
        WINRT_IMPL_AUTO(winrt::event_token) CreateResources(winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualControl, winrt::Microsoft::Graphics::Canvas::UI::CanvasCreateResourcesEventArgs> const& value) const;
        using CreateResources_revoker = impl::event_revoker<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl, &impl::abi_t<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl>::remove_CreateResources>;
        [[nodiscard]] CreateResources_revoker CreateResources(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualControl, winrt::Microsoft::Graphics::Canvas::UI::CanvasCreateResourcesEventArgs> const& value) const;
        WINRT_IMPL_AUTO(void) CreateResources(winrt::event_token const& token) const noexcept;
        [[nodiscard]] WINRT_IMPL_AUTO(bool) ReadyToDraw() const;
        WINRT_IMPL_AUTO(winrt::event_token) RegionsInvalidated(winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualControl, winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasRegionsInvalidatedEventArgs> const& value) const;
        using RegionsInvalidated_revoker = impl::event_revoker<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl, &impl::abi_t<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl>::remove_RegionsInvalidated>;
        [[nodiscard]] RegionsInvalidated_revoker RegionsInvalidated(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualControl, winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasRegionsInvalidatedEventArgs> const& value) const;
        WINRT_IMPL_AUTO(void) RegionsInvalidated(winrt::event_token const& token) const noexcept;
        WINRT_IMPL_AUTO(void) ClearColor(winrt::Windows::UI::Color const& value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::UI::Color) ClearColor() const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession) CreateDrawingSession(winrt::Windows::Foundation::Rect const& updateRectangle) const;
        WINRT_IMPL_AUTO(void) SuspendDrawingSession(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession const& drawingSession) const;
        WINRT_IMPL_AUTO(void) ResumeDrawingSession(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession const& drawingSession) const;
        WINRT_IMPL_AUTO(void) Invalidate() const;
        WINRT_IMPL_AUTO(void) Invalidate(winrt::Windows::Foundation::Rect const& region) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::Foundation::Size) Size() const;
        WINRT_IMPL_AUTO(void) RemoveFromVisualTree() const;
        [[nodiscard]] WINRT_IMPL_AUTO(bool) UseSharedDevice() const;
        WINRT_IMPL_AUTO(void) UseSharedDevice(bool value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(bool) ForceSoftwareRenderer() const;
        WINRT_IMPL_AUTO(void) ForceSoftwareRenderer(bool value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasDevice) CustomDevice() const;
        WINRT_IMPL_AUTO(void) CustomDevice(winrt::Microsoft::Graphics::Canvas::CanvasDevice const& value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(float) DpiScale() const;
        WINRT_IMPL_AUTO(void) DpiScale(float ratio) const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasVirtualControl<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasVirtualImageSource
    {
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Microsoft::UI::Xaml::Media::Imaging::VirtualSurfaceImageSource) Source() const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession) CreateDrawingSession(winrt::Windows::UI::Color const& clearColor, winrt::Windows::Foundation::Rect const& updateRectangle) const;
        WINRT_IMPL_AUTO(void) SuspendDrawingSession(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession const& drawingSession) const;
        WINRT_IMPL_AUTO(void) ResumeDrawingSession(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession const& drawingSession) const;
        WINRT_IMPL_AUTO(void) Invalidate() const;
        WINRT_IMPL_AUTO(void) Invalidate(winrt::Windows::Foundation::Rect const& region) const;
        WINRT_IMPL_AUTO(void) RaiseRegionsInvalidatedIfAny() const;
        WINRT_IMPL_AUTO(winrt::event_token) RegionsInvalidated(winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource, winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasRegionsInvalidatedEventArgs> const& value) const;
        using RegionsInvalidated_revoker = impl::event_revoker<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource, &impl::abi_t<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource>::remove_RegionsInvalidated>;
        [[nodiscard]] RegionsInvalidated_revoker RegionsInvalidated(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource, winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasRegionsInvalidatedEventArgs> const& value) const;
        WINRT_IMPL_AUTO(void) RegionsInvalidated(winrt::event_token const& token) const noexcept;
        WINRT_IMPL_AUTO(void) Resize(winrt::Windows::Foundation::Size const& size) const;
        WINRT_IMPL_AUTO(void) Resize(float width, float height) const;
        WINRT_IMPL_AUTO(void) Resize(float width, float height, float dpi) const;
        WINRT_IMPL_AUTO(void) Recreate(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::Foundation::Size) Size() const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Windows::Graphics::Imaging::BitmapSize) SizeInPixels() const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::CanvasAlphaMode) AlphaMode() const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasVirtualImageSource<D>;
    };
    template <typename D>
    struct consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasVirtualImageSourceFactory
    {
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource) CreateWithSize(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi const& resourceCreator, winrt::Windows::Foundation::Size const& size) const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource) CreateWithWidthAndHeight(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi const& resourceCreator, float width, float height) const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource) CreateWithWidthAndHeightAndDpi(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator, float width, float height, float dpi) const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasVirtualImageSource) CreateWithWidthAndHeightAndDpiAndAlphaMode(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator, float width, float height, float dpi, winrt::Microsoft::Graphics::Canvas::CanvasAlphaMode const& alphaMode) const;
    };
    template <> struct consume<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSourceFactory>
    {
        template <typename D> using type = consume_Microsoft_Graphics_Canvas_UI_Xaml_ICanvasVirtualImageSourceFactory<D>;
    };
}
#endif
