// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_UI_Hosting_Experimental_1_H
#define WINRT_Microsoft_UI_Hosting_Experimental_1_H
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Microsoft.UI.Hosting.Experimental.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Hosting::Experimental
{
    struct __declspec(empty_bases) IExpContentBridge :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpContentBridge>,
        impl::require<winrt::Microsoft::UI::Hosting::Experimental::IExpContentBridge, winrt::Windows::Foundation::IClosable>
    {
        IExpContentBridge(std::nullptr_t = nullptr) noexcept {}
        IExpContentBridge(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpCoreWindowBridge :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpCoreWindowBridge>
    {
        IExpCoreWindowBridge(std::nullptr_t = nullptr) noexcept {}
        IExpCoreWindowBridge(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpCoreWindowBridgeStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpCoreWindowBridgeStatics>
    {
        IExpCoreWindowBridgeStatics(std::nullptr_t = nullptr) noexcept {}
        IExpCoreWindowBridgeStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpDesktopWindowBridge :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpDesktopWindowBridge>
    {
        IExpDesktopWindowBridge(std::nullptr_t = nullptr) noexcept {}
        IExpDesktopWindowBridge(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpDesktopWindowBridgeStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpDesktopWindowBridgeStatics>
    {
        IExpDesktopWindowBridgeStatics(std::nullptr_t = nullptr) noexcept {}
        IExpDesktopWindowBridgeStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpDesktopWindowTopLevelHostStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpDesktopWindowTopLevelHostStatics>
    {
        IExpDesktopWindowTopLevelHostStatics(std::nullptr_t = nullptr) noexcept {}
        IExpDesktopWindowTopLevelHostStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpPopupWindowBridge :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpPopupWindowBridge>
    {
        IExpPopupWindowBridge(std::nullptr_t = nullptr) noexcept {}
        IExpPopupWindowBridge(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpPopupWindowBridgeStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpPopupWindowBridgeStatics>
    {
        IExpPopupWindowBridgeStatics(std::nullptr_t = nullptr) noexcept {}
        IExpPopupWindowBridgeStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpSystemVisualBridge :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpSystemVisualBridge>
    {
        IExpSystemVisualBridge(std::nullptr_t = nullptr) noexcept {}
        IExpSystemVisualBridge(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IExpSystemVisualBridgeStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IExpSystemVisualBridgeStatics>
    {
        IExpSystemVisualBridgeStatics(std::nullptr_t = nullptr) noexcept {}
        IExpSystemVisualBridgeStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
