// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_UI_Input_2_H
#define WINRT_Microsoft_UI_Input_2_H
#include "winrt/impl/Windows.System.1.h"
#include "winrt/impl/Microsoft.UI.Input.1.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Input
{
    struct KeyboardInput
    {
        KeyboardInput() = delete;
        static auto GetKeyStateForCurrentThread(winrt::Windows::System::VirtualKey const& virtualKey);
    };
}
#endif
